"use client";

import { useState } from "react";
import {
  Users,
  UserPlus,
  UserCheck,
  Calendar,
  TrendingUp,
  Mail,
  Globe,
  ArrowRight,
  RefreshCw,
  ExternalLink,
  Star,
} from "lucide-react";
import { useLeadData } from "@/lib/hooks/useLeadData";

const STATUS_CONFIG: Record<string, { color: string; bg: string; label: string }> = {
  new: { color: "text-blue-700", bg: "bg-blue-100", label: "New" },
  contacted: { color: "text-amber-700", bg: "bg-amber-100", label: "Contacted" },
  qualified: { color: "text-purple-700", bg: "bg-purple-100", label: "Qualified" },
  meeting_booked: { color: "text-green-700", bg: "bg-green-100", label: "Meeting Booked" },
  converted: { color: "text-emerald-700", bg: "bg-emerald-100", label: "Converted" },
  lost: { color: "text-slate-500", bg: "bg-slate-100", label: "Lost" },
};

function ScoreBadge({ score }: { score: number }) {
  if (score >= 70) return <span className="inline-flex items-center gap-1 rounded-full bg-red-100 px-2 py-0.5 text-xs font-semibold text-red-700"><Star className="h-3 w-3" /> {score}</span>;
  if (score >= 40) return <span className="inline-flex items-center gap-1 rounded-full bg-amber-100 px-2 py-0.5 text-xs font-semibold text-amber-700">{score}</span>;
  return <span className="inline-flex items-center gap-1 rounded-full bg-slate-100 px-2 py-0.5 text-xs font-semibold text-slate-600">{score}</span>;
}

function FunnelBar({ label, count, total, color }: { label: string; count: number; total: number; color: string }) {
  const pct = total > 0 ? Math.max((count / total) * 100, 2) : 0;
  return (
    <div className="flex items-center gap-3">
      <span className="w-28 text-sm text-slate-600 text-right">{label}</span>
      <div className="flex-1 h-8 bg-slate-100 rounded-lg overflow-hidden">
        <div className={`h-full ${color} rounded-lg flex items-center px-3 transition-all`} style={{ width: `${pct}%`, minWidth: count > 0 ? "40px" : "0" }}>
          <span className="text-xs font-bold text-white">{count}</span>
        </div>
      </div>
    </div>
  );
}

export default function LeadsPage() {
  const { loading, error, leads, stats, refresh } = useLeadData();
  const [filter, setFilter] = useState<string>("all");

  const filteredLeads = filter === "all" ? leads : leads.filter((l) => l.status === filter);

  return (
    <div className="min-h-screen bg-slate-50 p-6">
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
            <Users className="h-6 w-6 text-blue-600" />
            Lead Pipeline
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            Leads generated by SAMA agents — content, SEO, social, and ads
          </p>
        </div>
        <button onClick={refresh} className="flex items-center gap-2 rounded-lg bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm border hover:bg-slate-50">
          <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </div>

      {error && (
        <div className="mb-6 rounded-lg bg-red-50 border border-red-200 p-4 text-sm text-red-700">
          {error}
        </div>
      )}

      {/* KPI Cards */}
      {stats && (
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
          {[
            { label: "Total Leads", value: stats.total, icon: Users, color: "text-blue-600", bg: "bg-blue-50" },
            { label: "New", value: stats.new, icon: UserPlus, color: "text-indigo-600", bg: "bg-indigo-50" },
            { label: "Qualified", value: stats.qualified, icon: UserCheck, color: "text-purple-600", bg: "bg-purple-50" },
            { label: "Meetings", value: stats.meeting_booked, icon: Calendar, color: "text-green-600", bg: "bg-green-50" },
            { label: "Converted", value: stats.converted, icon: TrendingUp, color: "text-emerald-600", bg: "bg-emerald-50" },
          ].map((kpi) => (
            <div key={kpi.label} className={`rounded-xl ${kpi.bg} p-4 border`}>
              <div className="flex items-center gap-2 mb-1">
                <kpi.icon className={`h-4 w-4 ${kpi.color}`} />
                <span className="text-xs font-medium text-slate-500">{kpi.label}</span>
              </div>
              <span className="text-2xl font-bold text-slate-900">{kpi.value}</span>
            </div>
          ))}
        </div>
      )}

      {/* Funnel + Source Breakdown */}
      {stats && (
        <div className="grid md:grid-cols-2 gap-6 mb-6">
          {/* Funnel */}
          <div className="rounded-xl bg-white p-6 shadow-sm border">
            <h2 className="text-sm font-semibold text-slate-700 mb-4 flex items-center gap-2">
              <ArrowRight className="h-4 w-4" />
              Conversion Funnel
            </h2>
            <div className="space-y-3">
              <FunnelBar label="New" count={stats.new} total={stats.total} color="bg-blue-500" />
              <FunnelBar label="Contacted" count={stats.contacted} total={stats.total} color="bg-amber-500" />
              <FunnelBar label="Qualified" count={stats.qualified} total={stats.total} color="bg-purple-500" />
              <FunnelBar label="Meeting" count={stats.meeting_booked} total={stats.total} color="bg-green-500" />
              <FunnelBar label="Converted" count={stats.converted} total={stats.total} color="bg-emerald-500" />
            </div>
          </div>

          {/* Source Breakdown */}
          <div className="rounded-xl bg-white p-6 shadow-sm border">
            <h2 className="text-sm font-semibold text-slate-700 mb-4 flex items-center gap-2">
              <Globe className="h-4 w-4" />
              Leads by Source
            </h2>
            {stats.by_source && Object.keys(stats.by_source).length > 0 ? (
              <div className="space-y-2">
                {Object.entries(stats.by_source)
                  .sort(([, a], [, b]) => b - a)
                  .map(([source, count]) => (
                    <div key={source} className="flex items-center justify-between py-1.5 border-b border-slate-100 last:border-0">
                      <span className="text-sm text-slate-600 capitalize">{source}</span>
                      <span className="text-sm font-semibold text-slate-900">{count}</span>
                    </div>
                  ))}
              </div>
            ) : (
              <p className="text-sm text-slate-400">No source data yet</p>
            )}
          </div>
        </div>
      )}

      {/* Lead Table */}
      <div className="rounded-xl bg-white shadow-sm border">
        <div className="flex items-center justify-between p-4 border-b">
          <h2 className="text-sm font-semibold text-slate-700">All Leads</h2>
          <div className="flex gap-1">
            {["all", "new", "qualified", "meeting_booked", "converted"].map((f) => (
              <button
                key={f}
                onClick={() => setFilter(f)}
                className={`px-3 py-1 rounded-md text-xs font-medium transition-colors ${
                  filter === f ? "bg-blue-100 text-blue-700" : "text-slate-500 hover:bg-slate-100"
                }`}
              >
                {f === "all" ? "All" : (STATUS_CONFIG[f]?.label || f)}
              </button>
            ))}
          </div>
        </div>

        {loading ? (
          <div className="p-8 text-center text-sm text-slate-400">Loading leads...</div>
        ) : filteredLeads.length === 0 ? (
          <div className="p-8 text-center">
            <Mail className="h-8 w-8 text-slate-300 mx-auto mb-2" />
            <p className="text-sm text-slate-400">
              {filter === "all"
                ? "No leads yet. Leads will appear here when captured from SAMA-generated content."
                : `No leads with status "${STATUS_CONFIG[filter]?.label || filter}"`}
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="bg-slate-50 text-left text-xs font-medium text-slate-500 uppercase tracking-wider">
                  <th className="px-4 py-3">Contact</th>
                  <th className="px-4 py-3">Company</th>
                  <th className="px-4 py-3">Source</th>
                  <th className="px-4 py-3">Score</th>
                  <th className="px-4 py-3">Status</th>
                  <th className="px-4 py-3">Date</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {filteredLeads.map((lead) => {
                  const statusCfg = STATUS_CONFIG[lead.status] || STATUS_CONFIG.new;
                  return (
                    <tr key={lead.id} className="hover:bg-slate-50 transition-colors">
                      <td className="px-4 py-3">
                        <div className="font-medium text-slate-900">{lead.name || lead.email}</div>
                        {lead.name && <div className="text-xs text-slate-400">{lead.email}</div>}
                      </td>
                      <td className="px-4 py-3 text-slate-600">{lead.company || "—"}</td>
                      <td className="px-4 py-3">
                        <span className="text-xs text-slate-500 capitalize">{lead.utm_source || "direct"}</span>
                        {lead.source_url && (
                          <a href={lead.source_url} target="_blank" rel="noopener noreferrer" className="ml-1 inline-block">
                            <ExternalLink className="h-3 w-3 text-slate-400 hover:text-blue-500" />
                          </a>
                        )}
                      </td>
                      <td className="px-4 py-3"><ScoreBadge score={lead.score} /></td>
                      <td className="px-4 py-3">
                        <span className={`inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium ${statusCfg.bg} ${statusCfg.color}`}>
                          {statusCfg.label}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-xs text-slate-400">
                        {new Date(lead.created_at).toLocaleDateString()}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
